# Jekyll Configuration File

# Site settings
title: "我的个人博客"
description: "分享技术文章和生活感悟的个人博客"
author: "博主"
email: "wsywq94@163.com"
url: "https://wsywq.github.io"
baseurl: ""

# Social media
social:
  github: wsywq
  email: wsywq94@163.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
relative_links:
  enabled: true
  collections: true

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "博主"
      comments: true
      share: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-category
    tag: archive-tag
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

# Analytics
analytics:
  google: "GA_MEASUREMENT_ID"
  baidu: "BAIDU_ANALYTICS_ID"

# Search
search:
  enabled: true
  path: "/search.json"

# Theme settings
theme:
  name: "personal-blog"
  version: "1.0.0"

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - .github/
  - README.md
  - LICENSE
  - 个人博客项目需求文档.md
